# Einleitung {-}

tbc...

## Konventionen {-}

Das Buch ist als Ergänzung zur Data-Übung gedacht...

* Packages werden als `package()` gezeigt

## Aufgaben {-}

Aufgaben für die Studierenden können in unterschiedliche Formen in das Dokument eingebettet werden. 

1. Quiz
Mit dem `Webex-Package` können Quiz-Fragen zum Selbststudium bereitgestellt werden. Das Dokument kann allerdings nicht heruntergeladen oder Antworten gespeichert werden. Beispiele für verschiedene Möglichkeiten findest du [hier](https://marcohhu.github.io/data_kurs.github.io/notebooks/sandbox_quiz.html) 

2. Jupyter-Notebooks
Jupyter-Notebooks sind eine IDE-Alternative zu RStudio. Aus meiner Perspektive ist die Installation und Handhabe etwas komplizierter. Allerdings bieten Notebooks eine gute Möglichkeit um Aufgabenblätter zu formulieren, da Notebooks heruntergeladen und bearbeitet werden können (aber auch nur in Jupyter-Notebooks und nicht in RStudio). Auch dazu gibt es ein Beispiel aus einem anderen Tutorium siehe [hier](https://marcohhu.github.io/data_kurs.github.io/notebooks/vis.html)

3. R-Notebooks
Auch RStudio bietet ein Notebook Format an. Großer Vorteil: Das Notebook kann direkt von der Seite heruntergeladen und in Rstudio geöffnet sowie bearbeitet werden. Ein Beispiel findest du [hier](https://marcohhu.github.io/data_kurs.github.io/notebooks/sandbox.nb.html.html)